### PR TITLE
Remove second Scaffold

### PR DESCRIPTION
**Pull request by Selecao**
Do we need use Scaffold inside Scaffold?

### CODE REVIEW

**Comment by fzammetti** [comment]
I think that you're probably right, although there definitely are times when a Scaffold inside a Scaffold is something you'll need/want to do depending on your requirements and it's never really "wrong" in any way that I'm aware of.  In this case though - and without actually testing it to be sure - I suspect you're right and it's not, strictly speaking, necessary.

However, I'm going to not accept this merge request for just one reason: the code in the repo would then not match the code in the book, which may confuse readers.  While mismatches like that tend to be acceptable for outright bugs (so long as the code is then commented to indicate why it doesn't match the book), for something like this that isn't really a bug per se, I think it's better to not introduce that potential confusion.  

However, I wanted to leave this comment at least so if someone were to question it as you have, they may find this comment and have their question answered, as well as to say thanks for offering the contribution in the first place :)

**Comment by Selecao** [comment]
Thank you for your comprehensive answering, should I Delete branch now?
By the way I found the concern why you use two Scaffolds, because SnackBar in book example doesn't work without it (with `Scaffold.of(inContext).showSnackBar` method).

**Comment by fzammetti** [comment]
Ah, that sorta sounds familiar now that you mention it - it's been a while since I looked at this code... but what you say makes sense and does kind of ring a bell.  Thanks for, in effect, documenting that here :)

The branch, I believe, is only on your account, I only see master in this repo, so deleting it is up to you, won't do any harm here :)

**Comment by Selecao** [comment]
Ok, now i go further (this book is the milestone that i missed when starting play with flutter).

**Pull request closed without merging**
